// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKs2L0VOtngt1yWjueP5OAbNAFrz1pHy0',
    appId: '1:190598010115:web:af2668a54b5c0dd764c536',
    messagingSenderId: '190598010115',
    projectId: 'tasklieapp',
    authDomain: 'tasklieapp.firebaseapp.com',
    storageBucket: 'tasklieapp.appspot.com',
    measurementId: 'G-HWRT2Q2FC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJhndws0ruag-Sb1713d_c5vuOmzpkLYI',
    appId: '1:190598010115:android:137061216433e02664c536',
    messagingSenderId: '190598010115',
    projectId: 'tasklieapp',
    storageBucket: 'tasklieapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADD58kJh6Ti4xNd74nDvsUSMt8FhiTq_0',
    appId: '1:190598010115:ios:662d1239aa313acb64c536',
    messagingSenderId: '190598010115',
    projectId: 'tasklieapp',
    storageBucket: 'tasklieapp.appspot.com',
    iosClientId: '190598010115-qnrum9a2h3kro3ql4tu2p3iko5f1nf84.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasklieNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADD58kJh6Ti4xNd74nDvsUSMt8FhiTq_0',
    appId: '1:190598010115:ios:662d1239aa313acb64c536',
    messagingSenderId: '190598010115',
    projectId: 'tasklieapp',
    storageBucket: 'tasklieapp.appspot.com',
    iosClientId: '190598010115-qnrum9a2h3kro3ql4tu2p3iko5f1nf84.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasklieNew',
  );
}
